create table if not exists public.auditoria (
    id bigint generated by default as identity primary key,
    entidade text not null,
    entidade_id bigint,
    acao text not null,
    detalhes jsonb not null default '{}'::jsonb,
    criado_em timestamptz not null default now()
);

create index if not exists idx_auditoria_entidade on public.auditoria (entidade, entidade_id, criado_em desc);
create unique index if not exists idx_funcionarios_nome_ativo on public.funcionarios (lower(trim(nome))) where ativo = true;

alter table public.auditoria enable row level security;
revoke all on table public.auditoria from anon, authenticated;
grant select, insert on table public.auditoria to service_role;
grant usage, select on all sequences in schema public to service_role;