create table if not exists public.despesas (
    id bigint generated by default as identity primary key,
    data date not null,
    descricao text not null check (char_length(trim(descricao)) between 2 and 160),
    categoria text not null default 'Materiais' check (char_length(trim(categoria)) between 2 and 60),
    valor numeric(12, 2) not null check (valor > 0),
    observacao text check (observacao is null or char_length(observacao) <= 500),
    created_at timestamptz not null default now()
);

create index if not exists idx_despesas_data on public.despesas (data desc);
create index if not exists idx_despesas_categoria on public.despesas (categoria);

alter table public.despesas enable row level security;
revoke all on table public.despesas from anon, authenticated;
grant select, insert, update, delete on table public.despesas to service_role;
grant usage, select on all sequences in schema public to service_role;
