create table if not exists public.funcionarios (
    id bigint generated by default as identity primary key,
    nome text not null check (char_length(trim(nome)) between 2 and 120),
    cargo text not null default 'Operário' check (char_length(cargo) <= 80),
    valor_diaria numeric(12, 2) not null check (valor_diaria > 0),
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.ponto (
    id bigint generated by default as identity primary key,
    data date not null,
    funcionario_id bigint not null references public.funcionarios(id) on delete cascade,
    status text not null check (status in ('Trabalhou', 'Falta', 'Feriado')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ponto_data_funcionario_unique unique (data, funcionario_id)
);

create index if not exists idx_ponto_data on public.ponto (data);
create index if not exists idx_ponto_funcionario_data on public.ponto (funcionario_id, data);

alter table public.funcionarios enable row level security;
alter table public.ponto enable row level security;

revoke all on table public.funcionarios from anon, authenticated;
revoke all on table public.ponto from anon, authenticated;
grant select, insert, update, delete on table public.funcionarios to service_role;
grant select, insert, update, delete on table public.ponto to service_role;
grant usage, select on all sequences in schema public to service_role;
